# Generated by Django 3.1.12 on 2024-12-01 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241129_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to=settings.AUTH_USER_MODEL),
        ),
    ]
