# Generated by Django 3.1.12 on 2024-12-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_auto_20241129_1445'),
        ('market', '0003_auto_20241129_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='farms.farm'),
        ),
    ]
