# Generated by Django 3.1.12 on 2024-12-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20241201_1250'),
        ('market', '0004_order_farm'),
    ]

    operations = [
    ]
