# Generated by Django 4.2.1 on 2024-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='geo_loc',
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
