# Generated by Django 4.2.1 on 2024-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_remove_farm_geo_loc_farm_latitude_farm_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farms'),
        ),
    ]
