# Generated by Django 5.1.3 on 2024-12-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_auto_20241129_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
