# Generated by Django 3.1.12 on 2024-12-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_alter_application_id_alter_farm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
